-- Universidade e Sociedade | Gran Tietê
-- Execute este arquivo no Supabase: Project > SQL Editor > New query > Run.

create extension if not exists pgcrypto;

create table if not exists public.admin_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null default 'Administrador',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admin_profiles ap
    where ap.id = auth.uid()
      and ap.is_active = true
  );
$$;

create table if not exists public.platform_settings (
  id bigint generated by default as identity primary key,
  site_name text not null,
  institution_name text not null,
  hero_title text not null,
  hero_subtitle text not null,
  contact_email text not null default '',
  contact_phone text not null default '',
  city text not null default '',
  primary_color text not null default '#06284A',
  accent_color text not null default '#D79A43',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.legal_areas (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  icon text not null default '⚖',
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.legal_contents (
  id bigint generated by default as identity primary key,
  legal_area_id bigint not null references public.legal_areas(id) on delete restrict,
  title text not null,
  slug text not null unique,
  summary text not null default '',
  body text not null default '',
  source text not null default '',
  is_featured boolean not null default false,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lawyers (
  id bigint generated by default as identity primary key,
  name text not null,
  oab_number text not null default '',
  specialties text not null default '',
  city text not null default '',
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  notes text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.internships (
  id bigint generated by default as identity primary key,
  title text not null,
  organization text not null default '',
  description text not null default '',
  requirements text not null default '',
  contact text not null default '',
  deadline date,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text not null,
  organizer text not null default '',
  description text not null default '',
  location text not null default '',
  url text not null default '',
  event_date timestamptz not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.service_links (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  category text not null default '',
  url text not null default '',
  phone text not null default '',
  is_active boolean not null default true,
  display_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text not null default '',
  subject text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists idx_legal_areas_slug on public.legal_areas(slug);
create index if not exists idx_legal_contents_slug on public.legal_contents(slug);
create index if not exists idx_legal_contents_area on public.legal_contents(legal_area_id);
create index if not exists idx_events_date on public.events(event_date);
create index if not exists idx_messages_created_at on public.contact_messages(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_platform_settings_updated_at on public.platform_settings;
create trigger trg_platform_settings_updated_at
before update on public.platform_settings
for each row execute function public.set_updated_at();

drop trigger if exists trg_legal_contents_updated_at on public.legal_contents;
create trigger trg_legal_contents_updated_at
before update on public.legal_contents
for each row execute function public.set_updated_at();

alter table public.admin_profiles enable row level security;
alter table public.platform_settings enable row level security;
alter table public.legal_areas enable row level security;
alter table public.legal_contents enable row level security;
alter table public.lawyers enable row level security;
alter table public.internships enable row level security;
alter table public.events enable row level security;
alter table public.service_links enable row level security;
alter table public.contact_messages enable row level security;

-- Limpa policies anteriores, permitindo executar o arquivo mais de uma vez.
drop policy if exists "Admins can read own profile" on public.admin_profiles;
drop policy if exists "Admins can manage admin profiles" on public.admin_profiles;
drop policy if exists "Public can read platform settings" on public.platform_settings;
drop policy if exists "Admins can manage platform settings" on public.platform_settings;
drop policy if exists "Public can read active legal areas" on public.legal_areas;
drop policy if exists "Admins can manage legal areas" on public.legal_areas;
drop policy if exists "Public can read published legal contents" on public.legal_contents;
drop policy if exists "Admins can manage legal contents" on public.legal_contents;
drop policy if exists "Public can read active lawyers" on public.lawyers;
drop policy if exists "Admins can manage lawyers" on public.lawyers;
drop policy if exists "Public can read active internships" on public.internships;
drop policy if exists "Admins can manage internships" on public.internships;
drop policy if exists "Public can read active events" on public.events;
drop policy if exists "Admins can manage events" on public.events;
drop policy if exists "Public can read active service links" on public.service_links;
drop policy if exists "Admins can manage service links" on public.service_links;
drop policy if exists "Public can insert contact messages" on public.contact_messages;
drop policy if exists "Admins can manage contact messages" on public.contact_messages;

create policy "Admins can read own profile"
on public.admin_profiles for select
using (id = auth.uid() or public.is_admin());

create policy "Admins can manage admin profiles"
on public.admin_profiles for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read platform settings"
on public.platform_settings for select
using (true);

create policy "Admins can manage platform settings"
on public.platform_settings for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read active legal areas"
on public.legal_areas for select
using (is_active = true or public.is_admin());

create policy "Admins can manage legal areas"
on public.legal_areas for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read published legal contents"
on public.legal_contents for select
using (is_published = true or public.is_admin());

create policy "Admins can manage legal contents"
on public.legal_contents for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read active lawyers"
on public.lawyers for select
using (is_active = true or public.is_admin());

create policy "Admins can manage lawyers"
on public.lawyers for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read active internships"
on public.internships for select
using (is_active = true or public.is_admin());

create policy "Admins can manage internships"
on public.internships for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read active events"
on public.events for select
using (is_active = true or public.is_admin());

create policy "Admins can manage events"
on public.events for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can read active service links"
on public.service_links for select
using (is_active = true or public.is_admin());

create policy "Admins can manage service links"
on public.service_links for all
using (public.is_admin())
with check (public.is_admin());

create policy "Public can insert contact messages"
on public.contact_messages for insert
with check (true);

create policy "Admins can manage contact messages"
on public.contact_messages for all
using (public.is_admin())
with check (public.is_admin());

insert into public.platform_settings
(site_name, institution_name, hero_title, hero_subtitle, contact_email, contact_phone, city, primary_color, accent_color)
select
  'Universidade e Sociedade',
  'Gran Tietê Faculdade',
  'Plataforma Digital para Ampliação do Acesso à Justiça',
  'Informação jurídica, orientação cidadã e oportunidades ao seu alcance.',
  'contato@grantiete.edu.br',
  '',
  'Barra Bonita/SP',
  '#06284A',
  '#D79A43'
where not exists (select 1 from public.platform_settings);

insert into public.legal_areas (name, slug, description, icon, display_order)
select * from (values
  ('Direito do Consumidor', 'direito-do-consumidor', 'Orientações básicas sobre compras, cobranças, garantias, serviços e relações de consumo.', '🛒', 1),
  ('Direito de Família', 'direito-de-familia', 'Informações introdutórias sobre guarda, alimentos, união estável, casamento e proteção familiar.', '👨‍👩‍👧', 2),
  ('Direito Previdenciário', 'direito-previdenciario', 'Noções sobre benefícios, aposentadorias, INSS e documentação necessária.', '🧾', 3),
  ('Direito Trabalhista', 'direito-trabalhista', 'Conteúdo cidadão sobre contrato de trabalho, verbas, jornada e canais de orientação.', '💼', 4),
  ('Direitos Fundamentais', 'direitos-fundamentais', 'Acesso a direitos básicos, cidadania, órgãos públicos e garantias constitucionais.', '⚖', 5)
) as seed(name, slug, description, icon, display_order)
where not exists (select 1 from public.legal_areas);

insert into public.legal_contents (legal_area_id, title, slug, summary, body, source, is_featured, is_published)
select area.id, seed.title, seed.slug, seed.summary, seed.body, seed.source, true, true
from (values
  ('direito-do-consumidor', 'Como agir diante de cobrança indevida', 'como-agir-diante-de-cobranca-indevida', 'Passos simples para organizar informações, buscar solução administrativa e registrar reclamação.', 'Uma cobrança indevida deve ser tratada com calma e organização. Guarde comprovantes, protocolos, mensagens, contratos e qualquer documento relacionado. Entre em contato com a empresa solicitando esclarecimento e correção. Se não houver solução, procure canais de defesa do consumidor, como PROCON, plataformas oficiais de reclamação ou orientação jurídica qualificada. Este conteúdo é informativo e não substitui atendimento profissional.', 'Conteúdo educativo inicial da plataforma.'),
  ('direito-de-familia', 'Pensão alimentícia: informações iniciais', 'pensao-alimenticia-informacoes-iniciais', 'Entenda, em linguagem simples, a finalidade da pensão alimentícia e a importância da documentação.', 'A pensão alimentícia busca garantir necessidades essenciais de quem precisa de apoio financeiro. O valor depende da análise da necessidade de quem recebe e da possibilidade de quem paga. Antes de procurar orientação, reúna documentos pessoais, comprovantes de renda, despesas e informações sobre a rotina da criança ou dependente. Este conteúdo é informativo e não substitui atendimento profissional.', 'Conteúdo educativo inicial da plataforma.'),
  ('direito-previdenciario', 'Documentos úteis para orientação previdenciária', 'documentos-uteis-para-orientacao-previdenciaria', 'Lista de documentos que costumam ajudar na análise inicial de benefícios e aposentadorias.', 'Para buscar orientação previdenciária, costuma ser útil reunir documento pessoal, CPF, comprovante de residência, carteira de trabalho, carnês de contribuição, extrato CNIS, laudos médicos quando houver incapacidade e comunicações recebidas do INSS. A análise concreta depende do caso e deve ser realizada por profissional habilitado ou órgão competente.', 'Conteúdo educativo inicial da plataforma.'),
  ('direito-trabalhista', 'Direitos básicos na relação de trabalho', 'direitos-basicos-na-relacao-de-trabalho', 'Apresentação introdutória sobre jornada, salário, registro, férias e canais de orientação.', 'Em relações de trabalho, é importante guardar contrato, recibos, holerites, registros de ponto e mensagens relevantes. Dúvidas sobre registro, salário, férias, jornada e verbas rescisórias podem exigir orientação especializada. Procure canais oficiais ou atendimento jurídico quando houver insegurança. Este conteúdo é educativo e não substitui consulta profissional.', 'Conteúdo educativo inicial da plataforma.'),
  ('direitos-fundamentais', 'Onde buscar ajuda jurídica gratuita ou de baixo custo', 'onde-buscar-ajuda-juridica-gratuita-ou-de-baixo-custo', 'Conheça caminhos de orientação, serviços públicos e instituições que podem apoiar a população.', 'A população pode buscar orientação em órgãos públicos, defensorias, núcleos de prática jurídica, PROCONs, serviços da OAB, unidades acadêmicas e canais oficiais. A disponibilidade depende da cidade e do tipo de demanda. A plataforma organiza informações para facilitar o primeiro passo e aproximar cidadão, universidade e comunidade.', 'Conteúdo educativo inicial da plataforma.')
) as seed(area_slug, title, slug, summary, body, source)
join public.legal_areas area on area.slug = seed.area_slug
where not exists (select 1 from public.legal_contents);

insert into public.service_links (title, description, category, url, phone, display_order)
select * from (values
  ('OAB Barra Bonita', 'Canal institucional para informações e ações jurídicas locais.', 'Institucional', '', '', 1),
  ('PROCON', 'Orientação e registro de reclamações sobre relações de consumo.', 'Consumidor', '', '', 2),
  ('Defensoria Pública', 'Atendimento jurídico para pessoas que se enquadram nos critérios de atendimento.', 'Acesso à Justiça', '', '', 3),
  ('Núcleo de Prática Jurídica', 'Espaço acadêmico para orientação supervisionada, quando disponível.', 'Universidade', '', '', 4)
) as seed(title, description, category, url, phone, display_order)
where not exists (select 1 from public.service_links);

insert into public.events (title, organizer, description, location, url, event_date, is_active)
select * from (values
  ('Roda de Conversa: Cidadania e Acesso à Justiça', 'Gran Tietê Faculdade', 'Atividade aberta para aproximar a comunidade de informações jurídicas básicas.', 'Faculdade Gran Tietê', '', now() + interval '20 days', true),
  ('Plantão de Orientação Jurídica', 'OAB / Faculdade', 'Agenda piloto para encaminhamento de dúvidas e orientação inicial.', 'Barra Bonita/SP', '', now() + interval '35 days', true)
) as seed(title, organizer, description, location, url, event_date, is_active)
where not exists (select 1 from public.events);

insert into public.internships (title, organization, description, requirements, contact, deadline, is_active)
select
  'Cadastro de interesse para estágio jurídico',
  'Banco de Estágios da Plataforma',
  'Espaço para divulgar oportunidades e registrar interesse de estudantes.',
  'Estudantes do curso de Direito. Requisitos específicos serão informados em cada vaga.',
  'Atualize este contato na área administrativa.',
  current_date + 60,
  true
where not exists (select 1 from public.internships);

-- Depois de criar o primeiro usuário no Supabase Auth, execute o comando abaixo separadamente,
-- trocando o e-mail, para liberar o acesso administrativo:
--
-- insert into public.admin_profiles (id, name, role, is_active)
-- select id, 'Administrador', 'Administrador', true
-- from auth.users
-- where email = 'admin@grantiete.edu.br'
-- on conflict (id) do update set name = excluded.name, role = excluded.role, is_active = true;
